version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    ports:
      - '3307:3306'
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5433:5432'
  mongos:
    image: mongo:latest
    ports:
      - '27018:27017'
