use std::path::Path;

pub(crate) fn generate_readme_ts(path: &Path) -> String {
    let last_component = path.file_name().unwrap().to_str().unwrap();
    return format!("{last_component}\n================\n\nThis package is generated by TEO.\n")
}
